### ISSUE TITLE
Invalid IBANs considered valid

### ISSUE THREAD

**Issue by floSoX** [Simplify/ibantools#16]
### Expected behavior
According to https://www.iban.com/testibans the following IBANs are invalid:
- GB00HLFX11016111455365
- GB01BARC20714583608387
- GB02BARC20201530093451
- GB24BARC20201630093459
- GB2LABBY09012857201707
- GB68CITI18500483515538

### Actual behavior
This IBANs return `true` wtith `isValidIBAN()` method

### Steps to reproduce the behavior
https://runkit.com/embed/x3thocnrh9hl

```js
const ibantools = require('ibantools');
const iban_list = ['GB33BUKB20201555555555', 'GB94BARC10201530093459', 'GB94BARC20201530093459', 'GB96BARC202015300934591', 'GB02BARC20201530093451', 'GB68CITI18500483515538', 'GB24BARC20201630093459', 'GB12BARC20201530093A59', 'GB78BARCO0201530093459', 'GB2LABBY09012857201707', 'GB01BARC20714583608387', 'GB00HLFX11016111455365', 'US64SVBKUS6S3300958879'];
let res = [];
iban_list.forEach(function(iban) {
  res[iban] = ibantools.isValidIBAN(iban);
});
res;
```

**Comment by Simplify** [comment]
@floSoX Thanks for your issue report and sorry about late reaction. I'll address all IBAN numbers as separate points.

* GB68CITI18500483515538 and GB02BARC20201530093451 - Invalid account number
This library does not check validity of account numbers inside BBAN. In order to validate account number I should have a list/range of all valid accounts per bank per country inside this library to do it. If you know where I can get those for free, under license that allows usage in free/open source programs, let me know.
* GB24BARC20201630093459 - Bank Code not found and invalid account
Same as above. `BARC` is bank code, but I don't have list of bank codes from all UK banks to verify this. Only think I can do is to verify that bank code is in valid format (4 letters).
* GB2LABBY09012857201707 - Invalid IBAN checksum structure
This is bug and I'll address it this week. It's unlikely to happen in real world, basically someone needs to replace checksum digit with a letter that will still pass mod97-10 validation.
* GB01BARC20714583608387 and GB00HLFX11016111455365 - Invalid IBAN checksum
This is interesting and to be honest I have no idea what to do about it yet.

This is how IBAN checksum is calculated (according to ECBS - European Committee for Banking Standards):
```
// Lets take GB00HLFX11016111455365
// Move first 4 characters from IBAN to the end
HLFX11016111455365GB00
// replace characters with numbers, A is 10 - Z = 35
1721153311016111455365161100
// Take that number and divide it with 97, rest should be 1
1721153311016111455365161100 % 97 = 1
```
This makes IBAN valid. I tested validity of this IBAN on different pages and all say that IBAN is valid:
- https://www.xe.com/ibancalculator/
- https://arhs.github.io/iban.js/
- https://www.nordea.com/en/our-services/cashmanagement/iban-validator-and-information/iban-validator/
Only page that says otherwise is https://bank.codes/iban/validate/ with error message: "The checksum figure of 00 is invalid. The correct checksum figure is 97." This made me think and try to calculate checksum using country code and BBAN:
```
// Lets take GB00HLFX11016111455365
// Replace checksum with 00, result is same because checksum is 00
// Move first 4 characters from IBAN to the end
HLFX11016111455365GB00
// replace characters with numbers, A is 10 - Z = 35
1721153311016111455365161100
// Take that number and divide it with 97 to get rest
// 1721153311016111455365161100 % 97
1
// Extract that from 98 (98 - 1)
97
```
Checksum should be 97, according to this. I'll think about this, but probably the best way to validate IBAN checksum should be to recalculate checksum and compare it instead of validation that I do today.

**Comment by Simplify** [comment]
@floSoX Last two issues are solved (checksum calculation and checksum structure). New release is made, 2.2.0. Thanks a lot for your report.

**Comment by floSoX** [comment]
Nice job @Simplify!

Thank you for this new release!
