### ISSUE TITLE
Valid IBAN is detected as invalid

### ISSUE THREAD

**Issue by abelosorio** [Simplify/ibantools#7]
I'm getting this issue when using a valid IBAN from Costa Rica. The IBAN number is not mine, so I cannot include it in without authorization from its owner. Let me know if you need it and I can request the permissions.

### Expected behavior
```
ibanTools.isValidIBAN('CR25------------------')
// true
```

### Actual behavior
```
ibanTools.isValidIBAN('CR25------------------')
// false
```

### Steps to reproduce the behavior
  - Install `ibantools`.
  - Try to validate a valid IBAN.
  - Expect to return `true` but it returns `false`.

The IBAN code is valid. Anyway I validated it by using the IBAN checker (https://www.iban.com):

![image](https://user-images.githubusercontent.com/12383055/35806724-45f9acfc-0a5f-11e8-9339-d8cde28b674c.png)

### UPDATE

The complete IBAN code is: `CR25010200009074883572`

**Comment by Simplify** [comment]
Hi @abelosorio and thank you for reporting this. Sorry for delayed response, I had a flu last week. 

When I was building this library I used [official IBAN registry, revision 66](https://www.swift.com/sites/default/files/resources/swift_standards_ibanregistry.pdf) and Wikipedia IBAN page. Both of those had IBANs from Costa Rica on 21 chars. Wikipedia page is [changed on 18. november](https://en.wikipedia.org/w/index.php?title=International_Bank_Account_Number&oldid=810992979) and says 22 chars now. In last version of [official IBAN registry, release 78](https://www.swift.com/sites/default/files/resources/iban_registry.pdf) Costa Rica is on 22 chars. I can't see when they change it, because they don't show revision history any more. Apparently, [format was changed](http://www.ticotimes.net/2016/12/15/banks-iban-costa-rica) last year. 

I'll make new release today, after checking other other changes in last 12 revisions of standard that I missed.

**Comment by Simplify** [comment]
@abelosorio version 1.6.0 is released. That fixes this issue. Thank you for reporting this 👍

**Comment by abelosorio** [comment]
Thanks!!
